In [1]:
# Numpy Assignment
import numpy as np
import pandas as pd

In [13]:
# Question 1.) Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int32


In [17]:
# Question 2.) Given a NumPy array 'arr', check if its data type is float64.
# arr = np.array([1.5, 2.6, 3.7])

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)
#Yes data type of the array is float64

float64


In [27]:
# Question 3.) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([2+1j, 3+1j, 4+1j])
print(arr.dtype)

complex128


In [41]:
# Question 4.) Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1,2,3,4,5], int)
arr1 = arr.astype(np.float32)
print(arr1.dtype)

float32


In [45]:
# Question 5.) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.87878475845846, 2.38758478475878475, 3,85858374734984928498], np.float64)
arr1 = arr.astype(np.float32)
print(arr1.dtype)
print(arr1)

float32
[1.8787848e+00 2.3875847e+00 3.0000000e+00 8.5858374e+19]


In [51]:
# Question 6.) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    return f"Shape:{arr.shape}, Size:{arr.size}, Data:{arr.dtype}"

arr = np.array([1,2,3,4,5])
print(array_attributes(arr))

Shape:(5,), Size:5, Data:int32


In [61]:
# Question 7.) Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return f"Dimensionality : {arr.ndim}"

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array_dimension(arr))

Dimensionality : 2


In [65]:
# Question 8.) Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(item_size_info(arr))

(4, 40)


In [69]:
# Question 9.) Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr.dtype)
print(array_strides(arr))

int32
(20, 4)


In [71]:
# Question 10.) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(shape_stride_relationship(arr))

((2, 5), (20, 4))


In [81]:
# Question 11.) Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

arr = create_zeros_array(5)
print(arr)

[0. 0. 0. 0. 0.]


In [85]:
# Question 12.) Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones 
#               of size `rows x cols`.

def create_ones_matrix(rows, cols):
    return np.ones((rows,cols))

arr = create_ones_matrix(4,5)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
# Question 13.) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array 
#               with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start, stop, step):
    return np.arange(start,stop,step)

arr = generate_range_array(1,10,0.5)
print(arr)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [97]:
# Question 14.) Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a 
#               NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

arr = generate_linear_space(0.1,0.5,5)
print(arr)

[0.1 0.2 0.3 0.4 0.5]


In [105]:
# Question 15.) Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` 
#               using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n, dtype = int)

arr = create_identity_matrix(5)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [111]:
# Question 16.) Write a function that takes a Python list and converts it into a NumPy array.

def convert(lis):
    return np.array(lis)

lis = [1,2,3,4,5]
arr = convert(lis)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [129]:
# Question 17.) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Original array data type {arr.dtype}")

view_arr = arr.view().reshape((2,5))

print(f"View array shape {view_arr.shape}")
print(f"View array data type {view_arr.dtype}")
print(view_arr)

Original array data type int32
View array shape (2, 5)
View array data type int32
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [151]:
# Question 18.) Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concat(arr1,arr2):
    return np.concatenate((arr1,arr2), axis = 0)

arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[6,7,8,9,10]])

arr = concat(arr1,arr2)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [161]:
# Question 19.) Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

def concat(arr1,arr2):
    return np.concatenate((arr1,arr2), axis = 1)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9,10], [11,12,13,14]])

arr = concat(arr1,arr2)
print(arr)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6 11 12 13 14]]


In [163]:
# Question 20.) Write a function that vertically stacks multiple NumPy arrays given as a list.

def stacks(arrays):
    return np.vstack(arrays)

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
arr3 = np.array([[13,14,15], [16,17,18]])

arr = stacks([arr1,arr2,arr3])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [173]:
# Question 21.) Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create(start, stop, step):
    if (stop-start)%step == 0:
        stop += start

    return np.arange(start,stop,step)

arr = create(1,9,2)
print(arr)

[1 3 5 7 9]


In [175]:
# Question 22.) Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def create():
    return np.linspace(0,1,10)

arr = create()
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [181]:
# Question 23.) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def create():
    return np.logspace(1,1000,5)

arr = create()
print(arr)

[1.00000000e+001 5.62341325e+250             inf             inf
             inf]


In [191]:
# Question 24.) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

arr = np.random.randint(1,100, (5,3))
print(arr)

df = pd.DataFrame(arr)
df

[[98 62 86]
 [38 84 97]
 [ 7 99  6]
 [62 41 73]
 [93 66 34]]


0   1   2
0  98  62  86
1  38  84  97
2   7  99   6
3  62  41  73
4  93  66  34

In [209]:
# Question 25.) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros.
#               Use NumPy operations within the Pandas DataFrame.

def replace_zero(df,column):
    df[column] = np.where(df[column] < 0, 0, df[column])

df = pd.DataFrame([[-1,2,4,8,6], [-3,5,53,2,2], [-3,65,7,3,3]])

replace_zero(df,0)
df

0   1   2  3  4
0  0   2   4  8  6
1  0   5  53  2  2
2  0  65   7  3  3

In [213]:
# Question 26.) Access the 3rd element from the given NumPy array.
#                arr = np.array([10,20,30,40,50])

arr = np.array([10,20,30,40,50])
print(arr[2])

30


In [215]:
# Question 27.) Retrieve the element at index (1, 2) from the 2D NumPy array.
#               arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d[1][2])

6


In [221]:
# Question 28.) Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3,8,2,10,5,7])

print(arr[arr > 5])

[ 8 10  7]


In [225]:
# Question 29.) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])

[3 4 5 6]


In [229]:
# Question 30.) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(arr_2d[0:2, [1,2]])

[[2 3]
 [5 6]]


In [259]:
# Question 31.) Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

# NAIVE APPROACH
def extract(arr,indices):

    rows = [0] * indices.shape[0]
    cols = [0] * indices.shape[0]
    
    for i in range(indices.shape[0]):
        rows[i] = indices[i][0]
        cols[i] = indices[i][1]

    sliced_arr = np.zeros(len(rows), int)
    for i in range(len(rows)):
        sliced_arr[i] = arr[rows[i]][cols[i]]

    return sliced_arr
        

# A BETTER APPROACH
def extract_array(arr,indices):
    rows, cols = indices[:,0], indices[:,1]

    sliced_arr = arr[rows, cols]

    return sliced_arr


# Main function
if __name__ == "__main__":
    arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

    indices = np.array([[0, 2],
                        [1, 0],
                        [2, 1]])

    print(extract(arr,indices))
    print(extract_array(arr,indices))

[30 40 80]
[30 40 80]


In [261]:
# Question 32.) Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter(arr,threshold):
    return arr[arr>threshold]

arr = np.array([10,20,30,40,50])
threshold = 30
print(filter(arr,threshold))

[40 50]


In [265]:
# Question 33.) Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#               separate arrays for each dimension.

def extract(arr,rows,cols,depths):
    return arr[rows,cols,depths]

arr = np.array([[[10, 20, 30],
                 [40, 50, 60]],
                
                [[70, 80, 90],
                 [100, 110, 120]],
                
                [[130, 140, 150],
                 [160, 170, 180]]])

rows = np.array([0, 1, 2])
cols = np.array([1, 0, 1])
depths = np.array([2, 1, 0])

print(extract(arr,rows,cols,depths))

[ 60  80 160]


In [269]:
# Question 34.) Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def filter(arr,con1,con2):
    return arr[con1&con2]

arr = np.array([10,20,30,40,50,60])
con1 = arr > 20
con2 = arr%2==0

print(filter(arr,con1,con2))

[30 40 50 60]


In [289]:
# Question 35.) Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract(arr,arr1,arr2):
    return arr[arr1,arr2]

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])

arr1 = np.array([3,3])
arr2 = np.array([2,1])

print(extract(arr,arr1,arr2))

[120 110]


In [305]:
# Question 36.) Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.zeros((3,3), int)
arr + 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [317]:
# Question 37.) Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in 
#               arr1 using NumPy broadcasting.

arr1 = np.random.randint(1,10,(1,3))
print(arr1)

arr2 = np.random.randint(1,10,(3,4))
print(arr2)

arr1 @ arr2

[[6 7 7]]
[[6 7 9 5]
 [2 8 3 1]
 [8 3 9 2]]


array([[106, 119, 138,  51]])

In [337]:
# Question 38.) Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.random.randint(1,10,(4))
print('Array 1',arr1)

arr2 = np.random.randint(1,10,(4,3))
print('Array 2',arr2)

sliced_array = arr1[:arr2.shape[1]]
print("Added array")
arr2 + sliced_array

Array 1 [7 9 7 9]
Array 2 [[2 8 3]
 [6 7 3]
 [4 8 2]
 [6 3 4]]
Added array


array([[ 9, 17, 10],
       [13, 16, 10],
       [11, 17,  9],
       [13, 12, 11]])

In [339]:
# Question 39.) Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(1,10,(1,3))

arr1+arr2

array([[14, 13, 10],
       [ 6,  5,  2],
       [13, 12,  9]])

In [343]:
# Question 40.) Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. 
#               Handle the shape incompatibility.

arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(2,2))

sliced_array = arr1[:, :arr2.shape[0]]

sliced_array * arr2

array([[ 5, 14],
       [20, 32]])

In [351]:
# Question 41.) Calculate column-wise mean for the given array:

arr = np.array([[1,2,3], [4,5,6]])

np.mean(arr,axis = 0)

array([2.5, 3.5, 4.5])

In [353]:
# Question 42.) Find maximum value in each row of the given array:

arr = np.array([[1,2,3], [4,5,6]])
np.max(arr,axis = 1)

array([3, 6])

In [367]:
# Question 43.) For the given array, find indices of maximum value in each column.

arr = np.array([[1,2,3], [4,5,6]])
np.argmax(arr,axis = 0)

array([1, 1, 1], dtype=int64)

In [401]:
# Question 44.) For the given array, apply custom function to calculate moving sum along rows.

def moving_sum(arr):
    rows, cols = arr.shape
    result = np.zeros((rows, cols), dtype=int)

    for i in range(rows):
        for j in range(cols):
            result[i][j] = np.sum(arr[i,:j+1])

    return result

arr = np.array([[1,2,3], [4,5,6]])
print(moving_sum(arr))

[[ 1  3  6]
 [ 4  9 15]]


In [4]:
# Question 45.) In the given array, check if all elements in each column are even.

arr = np.array([[2,4,6], [3,5,7]])
print(np.all(arr % 2 == 0, axis=0))

[False False False]


In [26]:
# Question 46.) Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

def reshape_to_matrix(arr,m,n):
    return arr.reshape(m,n)

original_array = np.array([1,2,3,4,5,6])
arr1 = reshape_to_matrix(original_array,2,3)

print(arr1)

[[1 2 3]
 [4 5 6]]


In [28]:
# Question 47.) Create a function that takes a matrix as input and returns the flattened array.

def flatten_to_array(matrix):
    return matrix.flatten()

input_matrix = np.array([[1,2,3], [4,5,6]])
flatten_array = flatten_to_array(input_matrix)

print(flatten_array)

[1 2 3 4 5 6]


In [40]:
# Question 48.) Write a function that concatenates two given arrays along a specified axis.

def concat(array1,array2,axis):
    return np.concatenate((array1,array2),axis)

array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])

array = concat(array1,array2,0)

print(array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [68]:
# Question 49.) Create a function that splits an array into multiple sub-arrays along a specified axis.

def split_array(array,num,axis):
    return np.split(array,num,axis)

original_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

splited_array = split_array(original_array,3,axis = 0)
for idx,arr in enumerate(splited_array):
    print(f"{idx+1} array is {arr}")

1 array is [[1 2 3]]
2 array is [[4 5 6]]
3 array is [[7 8 9]]


In [82]:
# Question 50.) Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_N_delete(array,indices_to_insert,values_to_insert,indices_to_delete):
    array = np.insert(array,indices_to_insert,values_to_insert)
    array = np.delete(array,indices_to_delete)
    return array

if __name__ == "__main__":
    original_array = np.array([1,2,3,4,5])
    indices_to_insert = np.array([2,4])
    values_to_insert = np.array([10,11])
    indices_to_delete = np.array([1,3])

    modified_array = insert_N_delete(original_array,indices_to_insert,values_to_insert,indices_to_delete)

    print(modified_array)

[ 1 10  4 11  5]


In [102]:
# Question 51.) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#               Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1,10, (2,3))
print("Array1\n", arr1,"\n")

arr2 = np.random.randint(1,10, (2,3))
print("Array2\n", arr2,"\n")

print("Element wise added array\n", arr1+arr2)

Array1
 [[9 7 6]
 [3 5 8]] 

Array2
 [[5 5 7]
 [1 7 2]] 

Element wise added array
 [[14 12 13]
 [ 4 12 10]]


In [152]:
# Question 52.) Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. 
#               Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0,-1)
print("Array1\n", arr1, "\n")

arr2 = np.arange(1, 11)
print("Array2\n", arr2, "\n")

print("Element-wise subtracted array\n", arr1 - arr2)

Array1
 [10  9  8  7  6  5  4  3  2  1] 

Array2
 [ 1  2  3  4  5  6  7  8  9 10] 

Element-wise subtracted array
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [140]:
# Question 53.) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#               Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1,6,(1,5))
print("Array1\n", arr1,"\n")

arr2 = np.random.randint(1,6,(1,5))
print("Array2\n", arr2,"\n")

print("Element wise multiplied array\n", arr1*arr2)

Array1
 [[5 2 4 4 4]] 

Array2
 [[1 2 3 3 3]] 

Element wise multiplied array
 [[ 5  4 12 12 12]]


In [154]:
# Question 54.) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. 
#               Perform element-wise division of `arr1` by `arr2`.

arr1 = np.arange(2,11,step = 2)
print("Array1\n", arr1, "\n")

arr2 = np.arange(1, 6)
print("Array2\n", arr2, "\n")

print("Element-wise division array\n", arr1 / arr2)

Array1
 [ 2  4  6  8 10] 

Array2
 [1 2 3 4 5] 

Element-wise division array
 [2. 2. 2. 2. 2.]


In [162]:
# Question 55.) Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. 
#               Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1,6)
print("Array1\n", arr1, "\n")

arr2 = np.arange(5,0,-1)
print("Array2\n", arr2, "\n")

print("Element-wise division array\n", np.power(arr1,arr2))

Array1
 [1 2 3 4 5] 

Array2
 [5 4 3 2 1] 

Element-wise division array
 [ 1 16 27 16  5]


In [182]:
# Question 56.) Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

def count(arr,substring):
    count = np.array([s.count(substring) for s in arr])
    return np.sum(count)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count(arr,'hello'))

3


In [14]:
# Question 57.) Write a function that extracts uppercase characters from a NumPy array of strings.

def extract_uppercase(arr):
    upper_array = []

    for s in arr:
        upper_array.extend([char for char in s if char.isupper()])
    return upper_array

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_array = extract_uppercase(arr)
print(uppercase_array)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [16]:
# Question 58.) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

def replace(arr,old_substring, new_substring):
    return np.char.replace(arr,old_substring,new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace(arr,'a','b')
print(new_arr)

['bpple' 'bbnbnb' 'grbpe' 'pinebpple']


In [24]:
# Question 59.) Write a function that concatenates strings in a NumPy array element-wise.

def concat(arr1,arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

print(concat(arr1,arr2))

['HelloOpen' 'WorldAI']


In [28]:
# Question 60.) Write a function that finds the length of the longest string in a NumPy array.

def find_max(arr):
    max = 0
    for i in arr:
        if len(i) > max:
            max = len(i)
            
    return max

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(find_max(arr))

9


In [36]:
# Question 61.) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the
#               dataset using NumPy's functions.

dataset = np.random.randint(1,1001,size = 100)

print(f"Dataset: {dataset}")
print(f"Mean: {np.mean(dataset)}")
print(f"Median: {np.median(dataset)}")
print(f"Variance: {np.var(dataset)}")
print(f"Standard Deviation: {np.std(dataset)}")

Dataset: [322 711 228 629 693 141 720 510 857 964 761 286 690 937 571 377 244 282
 426 356 790  65 802 992 295  18  15 306 943 347 644 410 558 848 610 429
  61 938 843 889 372 108 183 218 360 884  15  22 967 401 192  11 590 467
 473 353 104 392 510 419 506 918 166 198 298 591 205 904 431 275  34 184
 674 105 305 891 665 138 905 279 490 577 498  83 374 888 798 486 978 643
  59 427 528 668 621  33 445 103 374   9]
Mean: 463.03
Median: 428.0
Variance: 83957.64910000002
Standard Deviation: 289.754463468641


In [38]:
# Question 62.) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

array = np.random.randint(1,101,size = 50)

print(f"Array: {array}")
print(f"25th Percentile: {np.percentile(array,25)}")
print(f"75th Percentile: {np.percentile(array,75)}")

Array: [83 61 81  7 34 69 57 90 72 96  7 95 61 52 28 60 70 37 96 15 94 34 56 71
 23 58 49 87 12 63 69  4 68 21 23 44  8 61 48 72 86 18  9 22 18 28 32 57
 80 79]
25th Percentile: 24.25
75th Percentile: 71.75


In [44]:
# Question 63.) Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using 
#               NumPy's `corrcoef` function.

arr1 = np.random.randint(1,101,size = 50)
arr2 = np.random.randint(1,101,size = 50)
print("Correlation betweemn two arrays is\n",np.corrcoef(arr1,arr2))

Correlation betweemn two arrays is
 [[ 1.         -0.09236465]
 [-0.09236465  1.        ]]


In [46]:
# Question 64.) Create two matrices and perform matrix multiplication using NumPy's `dot` function.

arr1 = np.random.randint(1,11,(3,4))
arr2 = np.random.randint(1,11,(4,4))

print(np.dot(arr1,arr2))

[[ 62 149  58 142]
 [ 57 122  83 166]
 [ 86 193  55 168]]


In [50]:
# Question 65.) Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and 
#               third quartiles.

array = np.random.randint(10, 1001, size=50)

print("Array:", array)
print("10th Median:", np.percentile(array, 10))
print("50th Median:", np.percentile(array, 50))
print("90th Percentile:", np.percentile(array, 90))
print("1st Quartile:", np.percentile(array, 25))
print("3rd Quartile:", np.percentile(array, 75))

Array: [172 744  75 839  35 327  26 933 543 853 941  78 940 450 839 519 863 378
 423 715 904 442 177 732 392 174 413 206 834 228 455 751 429 150 308 840
 126 827 799 989 359 966 936 325  55 736 213 409 402  92]
10th Median: 90.60000000000001
50th Median: 435.5
90th Percentile: 933.3
1st Quartile: 216.75
3rd Quartile: 832.25


In [58]:
# Question 66.) Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50, 60, 70, 50, 80, 90])
element = 50

indices = np.where(arr == element)
print(arr)
print(indices[0][0])

[10 20 30 40 50 60 70 50 80 90]
4


In [69]:
# Question 67.) Generate a random NumPy array and sort it in ascending order.

arr = np.random.randint(1,10,(1,10))
print("Unsorted array\n",arr)
print("Sorted array\n",np.sort(arr))

Unsorted array
 [[2 9 9 2 4 8 9 1 3 5]]
Sorted array
 [[1 2 2 3 4 5 8 9 9 9]]


In [73]:
# Question 68.) Filter elements >20  in the given NumPy array.

arr = np.array([12,25,6,42,8,30])
print("Filtered array", arr[arr>20])

Filtered array [25 42 30]


In [75]:
# Question 69.) Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1,5,8,12,15])
print("Filtered array", arr[arr%3 == 0])

Filtered array [12 15]


In [5]:
# Question 70.) Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10,20,30,40,50])
print("Filtered array", arr[(arr>=20) & (arr<=40)])

Filtered array [20 30 40]


In [13]:
# Question 71.) For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1,2,3])
print("Byte order of the array is: ",arr.dtype.byteorder)

Byte order of the array is:  =


In [19]:
# Question 72.) For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1,2,3], dtype = np.int32)

print("Byteorder before byteswap:", arr.dtype.byteorder)
arr.byteswap(inplace = True)
print("Byteorder after byteswap:", arr.dtype.byteorder)

Byteorder before byteswap: =
Byteorder after byteswap: =


In [25]:
# Question 73.) For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1,2,3], dtype = np.int32)

print("Byteorder before byteswap:", arr.dtype.byteorder)
arr1 = arr.newbyteorder()
print("Byteorder after byteswap:", arr1.dtype.byteorder)

Byteorder before byteswap: =
Byteorder after byteswap: >


In [33]:
# Question 74.) For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

import sys
arr = np.array([1,2,3], dtype = np.int32)

sys_endianness = sys.byteorder
arr_byteorder = arr.dtype.byteorder

if ((arr_byteorder == '<' and sys_endianness == 'big') or 
   (arr_byteorder == '>' and sys_endianness == 'little')):
    swapped_arr = arr.newbyteorder()
    print("Swapped array:",swapped_arr)
else:
    print("No need of swapping")

No need of swapping


In [37]:
# Question 75.) For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1,2,3], dtype = np.int32)

sys_endianness = sys.byteorder
arr_byteorder = arr.dtype.byteorder

if ((arr_byteorder == '<' and sys_endianness == 'big') or 
   (arr_byteorder == '>' and sys_endianness == 'little')):
    print("Byte swapping is necessary.")
else:
    print("No need of swapping")

No need of swapping


In [69]:
# Question 76.) Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. 
#               Check if modifying `copy_arr` affects `arr1`.

arr1 = np.random.randint(1,11,(10))
print("Array one:", arr1)

copy_arr = np.copy(arr1)
copy_arr[0] = 100

if(arr1[0] != copy_arr[0]):
    print("Change in copy_arr doesn't affected arr1")
else:
    print("Change in copy_arr affected arr1")

Array one: [ 4  8  1 10  9  8 10  4  7  7]
Change in copy_arr doesn't affected arr1


In [71]:
# Question 77.) Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. 
#               Modify an element in `view_slice` and observe if it changes the original `matrix`.

array = np.random.randint(1,11,(3,3))

print("Matrix\n",array,"\n")
view_slice = array[0:2,[0,2]]
print("View Slice\n",view_slice,"\n")

view_slice[0][0] = 100
if(array[0][0] != view_slice[0][0]):
    print("Change in copy_arr doesn't affected arr1")
else:
    print("Change in copy_arr affected arr1")

Matrix
 [[8 8 5]
 [5 6 3]
 [8 3 5]] 

View Slice
 [[8 5]
 [5 3]] 

Change in copy_arr doesn't affected arr1


In [91]:
# Question 78.) Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and 
#               broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.random.randint(1,13, (4,3))

view_b = array_a[0:2,[0,2]]
view_b = view_b+5

if(array_a[0][0] == view_b[0][0]):
    print("Broadcasting affected the original array")
else:
    print("Broadcasting didn't affected the original array")

Broadcasting didn't affected the original array


In [93]:
# Question 79.) Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2)
#               from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99

if(orig_array[0][0] == reshaped_view[0][0]):
    print("Broadcasting affected the original array")
else:
    print("Broadcasting didn't affected the original array")

Broadcasting affected the original array


In [97]:
# Question 80.) Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. 
#               Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1, 10, size=(3, 4))

data_copy = data[data > 5].copy()

data_copy[0] = 99

if(data[0][0] == data_copy[0]):
    print("Broadcasting affected the original array")
else:
    print("Broadcasting didn't affected the original array")

Broadcasting didn't affected the original array


In [103]:
# Question 81.) Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.random.randint(1, 10, size=(3, 4))
print("Array A\n",A,"\n")
B = np.random.randint(1, 10, size=(3, 4))
print("Array B\n",B,"\n")

print("Addition\n",A+B,"\n")
print("Subtraction\n",A-B)

Array A
 [[7 8 2 7]
 [1 9 5 1]
 [2 8 8 5]] 

Array B
 [[1 4 2 1]
 [7 5 9 9]
 [8 9 1 4]] 

Addition
 [[ 8 12  4  8]
 [ 8 14 14 10]
 [10 17  9  9]] 

Subtraction
 [[ 6  4  0  6]
 [-6  4 -4 -8]
 [-6 -1  7  1]]


In [105]:
# Question 82.) Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 10, size=(3, 2))
print("Array C\n",C,"\n")
D = np.random.randint(1, 10, size=(2, 4))
print("Array D\n",D,"\n")

print("Matrix Multiplication\n",C @ D)

Array C
 [[2 7]
 [6 4]
 [8 4]] 

Array D
 [[1 1 6 3]
 [1 7 1 9]] 

Matrix Multiplication
 [[ 9 51 19 69]
 [10 34 40 54]
 [12 36 52 60]]


In [111]:
# Question 83.) Create a matrix `E` and find its transpose

E = np.random.randint(1, 10, size=(3, 2))
print("Array E\n",E,"\n")

print("Transpose\n",np.transpose(E))

Array E
 [[9 6]
 [4 6]
 [9 1]] 

Transpose
 [[9 4 9]
 [6 6 1]]


In [115]:
# Question 84.) Generate a square matrix `F` and compute its determinant.

F = np.random.randint(1, 10, size=(3, 3))
print("Array F\n",F,"\n")

print("Determinant", np.linalg.det(F))

Array F
 [[7 5 3]
 [6 7 1]
 [1 2 6]] 

Determinant 119.99999999999997


In [121]:
# Question 85.) Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 10, size=(3, 3))
print("Array G\n",G,"\n")

print("Inverse\n", np.linalg.inv(G))

Array G
 [[4 2 6]
 [4 3 1]
 [2 3 2]] 

Inverse
 [[ 0.08333333  0.38888889 -0.44444444]
 [-0.16666667 -0.11111111  0.55555556]
 [ 0.16666667 -0.22222222  0.11111111]]
